apiVersion: v1
kind: Service
metadata:
  name: stepin-template
  labels:
    app: stepin-template
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: stepin-template
