apiVersion: v1
kind: Service
metadata:
  name: stepin-template
  labels:
    app: stepin-template
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: stepin-template
